<?php

namespace Proxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR.
 */
class __CG__EntityOrder extends \Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *               three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *               initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var bool flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();

    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        $this->__initializer__ = $initializer;
        $this->__cloner__ = $cloner;
    }

    /**
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', ''."\0".'Entity\\Order'."\0".'id', ''."\0".'Entity\\Order'."\0".'orderNo', ''."\0".'Entity\\Order'."\0".'amount', ''."\0".'Entity\\Order'."\0".'discount', ''."\0".'Entity\\Order'."\0".'transactionId', ''."\0".'Entity\\Order'."\0".'transactionStatus', ''."\0".'Entity\\Order'."\0".'errorCode', ''."\0".'Entity\\Order'."\0".'mihPayId', ''."\0".'Entity\\Order'."\0".'uniquePaymentId', ''."\0".'Entity\\Order'."\0".'paymentMode', ''."\0".'Entity\\Order'."\0".'paymentGatewayType', ''."\0".'Entity\\Order'."\0".'bankReferenceNumber', ''."\0".'Entity\\Order'."\0".'payuSystemStatus', ''."\0".'Entity\\Order'."\0".'createdOn', ''."\0".'Entity\\Order'."\0".'student');
        }

        return array('__isInitialized__', ''."\0".'Entity\\Order'."\0".'id', ''."\0".'Entity\\Order'."\0".'orderNo', ''."\0".'Entity\\Order'."\0".'amount', ''."\0".'Entity\\Order'."\0".'discount', ''."\0".'Entity\\Order'."\0".'transactionId', ''."\0".'Entity\\Order'."\0".'transactionStatus', ''."\0".'Entity\\Order'."\0".'errorCode', ''."\0".'Entity\\Order'."\0".'mihPayId', ''."\0".'Entity\\Order'."\0".'uniquePaymentId', ''."\0".'Entity\\Order'."\0".'paymentMode', ''."\0".'Entity\\Order'."\0".'paymentGatewayType', ''."\0".'Entity\\Order'."\0".'bankReferenceNumber', ''."\0".'Entity\\Order'."\0".'payuSystemStatus', ''."\0".'Entity\\Order'."\0".'createdOn', ''."\0".'Entity\\Order'."\0".'student');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if (!$this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (!array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy.
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) parent::getId();
        }

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritdoc}
     */
    public function setOrderNo($orderNo)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderNo', array($orderNo));

        return parent::setOrderNo($orderNo);
    }

    /**
     * {@inheritdoc}
     */
    public function getOrderNo()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderNo', array());

        return parent::getOrderNo();
    }

    /**
     * {@inheritdoc}
     */
    public function setAmount($amount)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', array($amount));

        return parent::setAmount($amount);
    }

    /**
     * {@inheritdoc}
     */
    public function getAmount()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', array());

        return parent::getAmount();
    }

    /**
     * {@inheritdoc}
     */
    public function setDiscount($discount)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', array($discount));

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritdoc}
     */
    public function getDiscount()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', array());

        return parent::getDiscount();
    }

    /**
     * {@inheritdoc}
     */
    public function setTransactionId($transactionId)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionId', array($transactionId));

        return parent::setTransactionId($transactionId);
    }

    /**
     * {@inheritdoc}
     */
    public function getTransactionId()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionId', array());

        return parent::getTransactionId();
    }

    /**
     * {@inheritdoc}
     */
    public function setTransactionStatus($transactionStatus)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionStatus', array($transactionStatus));

        return parent::setTransactionStatus($transactionStatus);
    }

    /**
     * {@inheritdoc}
     */
    public function getTransactionStatus()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionStatus', array());

        return parent::getTransactionStatus();
    }

    /**
     * {@inheritdoc}
     */
    public function setErrorCode($errorCode)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setErrorCode', array($errorCode));

        return parent::setErrorCode($errorCode);
    }

    /**
     * {@inheritdoc}
     */
    public function getErrorCode()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErrorCode', array());

        return parent::getErrorCode();
    }

    /**
     * {@inheritdoc}
     */
    public function setMihPayId($mihPayId)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMihPayId', array($mihPayId));

        return parent::setMihPayId($mihPayId);
    }

    /**
     * {@inheritdoc}
     */
    public function getMihPayId()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMihPayId', array());

        return parent::getMihPayId();
    }

    /**
     * {@inheritdoc}
     */
    public function setUniquePaymentId($uniquePaymentId)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniquePaymentId', array($uniquePaymentId));

        return parent::setUniquePaymentId($uniquePaymentId);
    }

    /**
     * {@inheritdoc}
     */
    public function getUniquePaymentId()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniquePaymentId', array());

        return parent::getUniquePaymentId();
    }

    /**
     * {@inheritdoc}
     */
    public function setPaymentMode($paymentMode)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMode', array($paymentMode));

        return parent::setPaymentMode($paymentMode);
    }

    /**
     * {@inheritdoc}
     */
    public function getPaymentMode()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMode', array());

        return parent::getPaymentMode();
    }

    /**
     * {@inheritdoc}
     */
    public function setPaymentGatewayType($paymentGatewayType)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentGatewayType', array($paymentGatewayType));

        return parent::setPaymentGatewayType($paymentGatewayType);
    }

    /**
     * {@inheritdoc}
     */
    public function getPaymentGatewayType()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentGatewayType', array());

        return parent::getPaymentGatewayType();
    }

    /**
     * {@inheritdoc}
     */
    public function setBankReferenceNumber($bankReferenceNumber)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankReferenceNumber', array($bankReferenceNumber));

        return parent::setBankReferenceNumber($bankReferenceNumber);
    }

    /**
     * {@inheritdoc}
     */
    public function getBankReferenceNumber()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankReferenceNumber', array());

        return parent::getBankReferenceNumber();
    }

    /**
     * {@inheritdoc}
     */
    public function setPayuSystemStatus($payuSystemStatus)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayuSystemStatus', array($payuSystemStatus));

        return parent::setPayuSystemStatus($payuSystemStatus);
    }

    /**
     * {@inheritdoc}
     */
    public function getPayuSystemStatus()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayuSystemStatus', array());

        return parent::getPayuSystemStatus();
    }

    /**
     * {@inheritdoc}
     */
    public function setCreatedOn($createdOn)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', array($createdOn));

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritdoc}
     */
    public function getCreatedOn()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', array());

        return parent::getCreatedOn();
    }

    /**
     * {@inheritdoc}
     */
    public function setStudent(\Entity\Student $student = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudent', array($student));

        return parent::setStudent($student);
    }

    /**
     * {@inheritdoc}
     */
    public function getStudent()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudent', array());

        return parent::getStudent();
    }
}
