<?php

namespace Proxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR.
 */
class __CG__EntityAdvertisement extends \Entity\Advertisement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *               three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *               initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var bool flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();

    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        $this->__initializer__ = $initializer;
        $this->__cloner__ = $cloner;
    }

    /**
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', ''."\0".'Entity\\Advertisement'."\0".'id', ''."\0".'Entity\\Advertisement'."\0".'headline', ''."\0".'Entity\\Advertisement'."\0".'descriptionLine1', ''."\0".'Entity\\Advertisement'."\0".'descriptionLine2', ''."\0".'Entity\\Advertisement'."\0".'descriptionLine3', ''."\0".'Entity\\Advertisement'."\0".'displayUrl', ''."\0".'Entity\\Advertisement'."\0".'targetDomain', ''."\0".'Entity\\Advertisement'."\0".'destinationUrl', ''."\0".'Entity\\Advertisement'."\0".'idPattern', ''."\0".'Entity\\Advertisement'."\0".'replaceId', ''."\0".'Entity\\Advertisement'."\0".'targetPattern', ''."\0".'Entity\\Advertisement'."\0".'snippetType', ''."\0".'Entity\\Advertisement'."\0".'snippet', ''."\0".'Entity\\Advertisement'."\0".'domainName', ''."\0".'Entity\\Advertisement'."\0".'domIdentifierType', ''."\0".'Entity\\Advertisement'."\0".'domIdentifierName', ''."\0".'Entity\\Advertisement'."\0".'position', ''."\0".'Entity\\Advertisement'."\0".'width', ''."\0".'Entity\\Advertisement'."\0".'height', ''."\0".'Entity\\Advertisement'."\0".'note', ''."\0".'Entity\\Advertisement'."\0".'activeFrom', ''."\0".'Entity\\Advertisement'."\0".'activeTo', ''."\0".'Entity\\Advertisement'."\0".'createdOn', ''."\0".'Entity\\Advertisement'."\0".'createdBy', ''."\0".'Entity\\Advertisement'."\0".'updatedOn', ''."\0".'Entity\\Advertisement'."\0".'updatedBy', ''."\0".'Entity\\Advertisement'."\0".'status', ''."\0".'Entity\\Advertisement'."\0".'pluginComponent', ''."\0".'Entity\\Advertisement'."\0".'adType');
        }

        return array('__isInitialized__', ''."\0".'Entity\\Advertisement'."\0".'id', ''."\0".'Entity\\Advertisement'."\0".'headline', ''."\0".'Entity\\Advertisement'."\0".'descriptionLine1', ''."\0".'Entity\\Advertisement'."\0".'descriptionLine2', ''."\0".'Entity\\Advertisement'."\0".'descriptionLine3', ''."\0".'Entity\\Advertisement'."\0".'displayUrl', ''."\0".'Entity\\Advertisement'."\0".'targetDomain', ''."\0".'Entity\\Advertisement'."\0".'destinationUrl', ''."\0".'Entity\\Advertisement'."\0".'idPattern', ''."\0".'Entity\\Advertisement'."\0".'replaceId', ''."\0".'Entity\\Advertisement'."\0".'targetPattern', ''."\0".'Entity\\Advertisement'."\0".'snippetType', ''."\0".'Entity\\Advertisement'."\0".'snippet', ''."\0".'Entity\\Advertisement'."\0".'domainName', ''."\0".'Entity\\Advertisement'."\0".'domIdentifierType', ''."\0".'Entity\\Advertisement'."\0".'domIdentifierName', ''."\0".'Entity\\Advertisement'."\0".'position', ''."\0".'Entity\\Advertisement'."\0".'width', ''."\0".'Entity\\Advertisement'."\0".'height', ''."\0".'Entity\\Advertisement'."\0".'note', ''."\0".'Entity\\Advertisement'."\0".'activeFrom', ''."\0".'Entity\\Advertisement'."\0".'activeTo', ''."\0".'Entity\\Advertisement'."\0".'createdOn', ''."\0".'Entity\\Advertisement'."\0".'createdBy', ''."\0".'Entity\\Advertisement'."\0".'updatedOn', ''."\0".'Entity\\Advertisement'."\0".'updatedBy', ''."\0".'Entity\\Advertisement'."\0".'status', ''."\0".'Entity\\Advertisement'."\0".'pluginComponent', ''."\0".'Entity\\Advertisement'."\0".'adType');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if (!$this->__isInitialized__) {
            $this->__initializer__ = function (Advertisement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (!array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy.
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) parent::getId();
        }

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritdoc}
     */
    public function setHeadline($headline)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeadline', array($headline));

        return parent::setHeadline($headline);
    }

    /**
     * {@inheritdoc}
     */
    public function getHeadline()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeadline', array());

        return parent::getHeadline();
    }

    /**
     * {@inheritdoc}
     */
    public function setDescriptionLine1($descriptionLine1)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionLine1', array($descriptionLine1));

        return parent::setDescriptionLine1($descriptionLine1);
    }

    /**
     * {@inheritdoc}
     */
    public function getDescriptionLine1()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionLine1', array());

        return parent::getDescriptionLine1();
    }

    /**
     * {@inheritdoc}
     */
    public function setDescriptionLine2($descriptionLine2)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionLine2', array($descriptionLine2));

        return parent::setDescriptionLine2($descriptionLine2);
    }

    /**
     * {@inheritdoc}
     */
    public function getDescriptionLine2()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionLine2', array());

        return parent::getDescriptionLine2();
    }

    /**
     * {@inheritdoc}
     */
    public function setDescriptionLine3($descriptionLine3)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionLine3', array($descriptionLine3));

        return parent::setDescriptionLine3($descriptionLine3);
    }

    /**
     * {@inheritdoc}
     */
    public function getDescriptionLine3()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionLine3', array());

        return parent::getDescriptionLine3();
    }

    /**
     * {@inheritdoc}
     */
    public function setDisplayUrl($displayUrl)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayUrl', array($displayUrl));

        return parent::setDisplayUrl($displayUrl);
    }

    /**
     * {@inheritdoc}
     */
    public function getDisplayUrl()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayUrl', array());

        return parent::getDisplayUrl();
    }

    /**
     * {@inheritdoc}
     */
    public function setTargetDomain($targetDomain)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTargetDomain', array($targetDomain));

        return parent::setTargetDomain($targetDomain);
    }

    /**
     * {@inheritdoc}
     */
    public function getTargetDomain()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTargetDomain', array());

        return parent::getTargetDomain();
    }

    /**
     * {@inheritdoc}
     */
    public function setDestinationUrl($destinationUrl)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinationUrl', array($destinationUrl));

        return parent::setDestinationUrl($destinationUrl);
    }

    /**
     * {@inheritdoc}
     */
    public function getDestinationUrl()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinationUrl', array());

        return parent::getDestinationUrl();
    }

    /**
     * {@inheritdoc}
     */
    public function setIdPattern($idPattern)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPattern', array($idPattern));

        return parent::setIdPattern($idPattern);
    }

    /**
     * {@inheritdoc}
     */
    public function getIdPattern()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPattern', array());

        return parent::getIdPattern();
    }

    /**
     * {@inheritdoc}
     */
    public function setReplaceId($replaceId)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReplaceId', array($replaceId));

        return parent::setReplaceId($replaceId);
    }

    /**
     * {@inheritdoc}
     */
    public function getReplaceId()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReplaceId', array());

        return parent::getReplaceId();
    }

    /**
     * {@inheritdoc}
     */
    public function setTargetPattern($targetPattern)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTargetPattern', array($targetPattern));

        return parent::setTargetPattern($targetPattern);
    }

    /**
     * {@inheritdoc}
     */
    public function getTargetPattern()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTargetPattern', array());

        return parent::getTargetPattern();
    }

    /**
     * {@inheritdoc}
     */
    public function setSnippetType($snippetType)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSnippetType', array($snippetType));

        return parent::setSnippetType($snippetType);
    }

    /**
     * {@inheritdoc}
     */
    public function getSnippetType()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSnippetType', array());

        return parent::getSnippetType();
    }

    /**
     * {@inheritdoc}
     */
    public function setSnippet($snippet)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSnippet', array($snippet));

        return parent::setSnippet($snippet);
    }

    /**
     * {@inheritdoc}
     */
    public function getSnippet()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSnippet', array());

        return parent::getSnippet();
    }

    /**
     * {@inheritdoc}
     */
    public function setDomainName($domainName)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomainName', array($domainName));

        return parent::setDomainName($domainName);
    }

    /**
     * {@inheritdoc}
     */
    public function getDomainName()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomainName', array());

        return parent::getDomainName();
    }

    /**
     * {@inheritdoc}
     */
    public function setDomIdentifierType($domIdentifierType)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomIdentifierType', array($domIdentifierType));

        return parent::setDomIdentifierType($domIdentifierType);
    }

    /**
     * {@inheritdoc}
     */
    public function getDomIdentifierType()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomIdentifierType', array());

        return parent::getDomIdentifierType();
    }

    /**
     * {@inheritdoc}
     */
    public function setDomIdentifierName($domIdentifierName)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomIdentifierName', array($domIdentifierName));

        return parent::setDomIdentifierName($domIdentifierName);
    }

    /**
     * {@inheritdoc}
     */
    public function getDomIdentifierName()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomIdentifierName', array());

        return parent::getDomIdentifierName();
    }

    /**
     * {@inheritdoc}
     */
    public function setPosition($position)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritdoc}
     */
    public function getPosition()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

    /**
     * {@inheritdoc}
     */
    public function setWidth($width)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidth', array($width));

        return parent::setWidth($width);
    }

    /**
     * {@inheritdoc}
     */
    public function getWidth()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidth', array());

        return parent::getWidth();
    }

    /**
     * {@inheritdoc}
     */
    public function setHeight($height)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', array($height));

        return parent::setHeight($height);
    }

    /**
     * {@inheritdoc}
     */
    public function getHeight()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', array());

        return parent::getHeight();
    }

    /**
     * {@inheritdoc}
     */
    public function setNote($note)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', array($note));

        return parent::setNote($note);
    }

    /**
     * {@inheritdoc}
     */
    public function getNote()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', array());

        return parent::getNote();
    }

    /**
     * {@inheritdoc}
     */
    public function setActiveFrom($activeFrom)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveFrom', array($activeFrom));

        return parent::setActiveFrom($activeFrom);
    }

    /**
     * {@inheritdoc}
     */
    public function getActiveFrom()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveFrom', array());

        return parent::getActiveFrom();
    }

    /**
     * {@inheritdoc}
     */
    public function setActiveTo($activeTo)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveTo', array($activeTo));

        return parent::setActiveTo($activeTo);
    }

    /**
     * {@inheritdoc}
     */
    public function getActiveTo()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveTo', array());

        return parent::getActiveTo();
    }

    /**
     * {@inheritdoc}
     */
    public function setCreatedOn($createdOn)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', array($createdOn));

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritdoc}
     */
    public function getCreatedOn()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', array());

        return parent::getCreatedOn();
    }

    /**
     * {@inheritdoc}
     */
    public function setCreatedBy($createdBy)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritdoc}
     */
    public function getCreatedBy()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritdoc}
     */
    public function setUpdatedOn($updatedOn)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', array($updatedOn));

        return parent::setUpdatedOn($updatedOn);
    }

    /**
     * {@inheritdoc}
     */
    public function getUpdatedOn()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', array());

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritdoc}
     */
    public function setUpdatedBy($updatedBy)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', array($updatedBy));

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritdoc}
     */
    public function getUpdatedBy()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', array());

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritdoc}
     */
    public function setStatus($status)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritdoc}
     */
    public function getStatus()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritdoc}
     */
    public function setPluginComponent(\Entity\PluginComponent $pluginComponent = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPluginComponent', array($pluginComponent));

        return parent::setPluginComponent($pluginComponent);
    }

    /**
     * {@inheritdoc}
     */
    public function getPluginComponent()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPluginComponent', array());

        return parent::getPluginComponent();
    }

    /**
     * {@inheritdoc}
     */
    public function setAdType(\Entity\AdType $adType = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdType', array($adType));

        return parent::setAdType($adType);
    }

    /**
     * {@inheritdoc}
     */
    public function getAdType()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdType', array());

        return parent::getAdType();
    }
}
