<?php

namespace Proxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR.
 */
class __CG__EntityJackpotGame extends \Entity\JackpotGame implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *               three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *               initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var bool flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];

    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        $this->__initializer__ = $initializer;
        $this->__cloner__ = $cloner;
    }

    /**
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', ''."\0".'Entity\\JackpotGame'."\0".'id', ''."\0".'Entity\\JackpotGame'."\0".'totalUsersParticipated', ''."\0".'Entity\\JackpotGame'."\0".'totalNumberOfBids', ''."\0".'Entity\\JackpotGame'."\0".'longestBidDuration', ''."\0".'Entity\\JackpotGame'."\0".'lastBidDuration', ''."\0".'Entity\\JackpotGame'."\0".'startedOn', ''."\0".'Entity\\JackpotGame'."\0".'finishedOn', ''."\0".'Entity\\JackpotGame'."\0".'createdAt', ''."\0".'Entity\\JackpotGame'."\0".'updatedAt', ''."\0".'Entity\\JackpotGame'."\0".'jackpot', ''."\0".'Entity\\JackpotGame'."\0".'longestBidWinnerUser', ''."\0".'Entity\\JackpotGame'."\0".'lastBidWinnerUser', 'gameUsers'];
        }

        return ['__isInitialized__', ''."\0".'Entity\\JackpotGame'."\0".'id', ''."\0".'Entity\\JackpotGame'."\0".'totalUsersParticipated', ''."\0".'Entity\\JackpotGame'."\0".'totalNumberOfBids', ''."\0".'Entity\\JackpotGame'."\0".'longestBidDuration', ''."\0".'Entity\\JackpotGame'."\0".'lastBidDuration', ''."\0".'Entity\\JackpotGame'."\0".'startedOn', ''."\0".'Entity\\JackpotGame'."\0".'finishedOn', ''."\0".'Entity\\JackpotGame'."\0".'createdAt', ''."\0".'Entity\\JackpotGame'."\0".'updatedAt', ''."\0".'Entity\\JackpotGame'."\0".'jackpot', ''."\0".'Entity\\JackpotGame'."\0".'longestBidWinnerUser', ''."\0".'Entity\\JackpotGame'."\0".'lastBidWinnerUser', 'gameUsers'];
    }

    public function __wakeup()
    {
        if (!$this->__isInitialized__) {
            $this->__initializer__ = function (JackpotGame $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (!array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };
        }
    }

    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy.
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritdoc}
     *
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) parent::getId();
        }

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritdoc}
     */
    public function setTotalUsersParticipated($totalUsersParticipated)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalUsersParticipated', [$totalUsersParticipated]);

        return parent::setTotalUsersParticipated($totalUsersParticipated);
    }

    /**
     * {@inheritdoc}
     */
    public function getTotalUsersParticipated()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalUsersParticipated', []);

        return parent::getTotalUsersParticipated();
    }

    /**
     * {@inheritdoc}
     */
    public function setTotalNumberOfBids($totalNumberOfBids)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalNumberOfBids', [$totalNumberOfBids]);

        return parent::setTotalNumberOfBids($totalNumberOfBids);
    }

    /**
     * {@inheritdoc}
     */
    public function getTotalNumberOfBids()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalNumberOfBids', []);

        return parent::getTotalNumberOfBids();
    }

    /**
     * {@inheritdoc}
     */
    public function setLongestBidDuration($longestBidDuration)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongestBidDuration', [$longestBidDuration]);

        return parent::setLongestBidDuration($longestBidDuration);
    }

    /**
     * {@inheritdoc}
     */
    public function getLongestBidDuration()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongestBidDuration', []);

        return parent::getLongestBidDuration();
    }

    /**
     * {@inheritdoc}
     */
    public function setLastBidDuration($lastBidDuration)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastBidDuration', [$lastBidDuration]);

        return parent::setLastBidDuration($lastBidDuration);
    }

    /**
     * {@inheritdoc}
     */
    public function getLastBidDuration()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastBidDuration', []);

        return parent::getLastBidDuration();
    }

    /**
     * {@inheritdoc}
     */
    public function setStartedOn($startedOn)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartedOn', [$startedOn]);

        return parent::setStartedOn($startedOn);
    }

    /**
     * {@inheritdoc}
     */
    public function getStartedOn()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartedOn', []);

        return parent::getStartedOn();
    }

    /**
     * {@inheritdoc}
     */
    public function setFinishedOn($finishedOn)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinishedOn', [$finishedOn]);

        return parent::setFinishedOn($finishedOn);
    }

    /**
     * {@inheritdoc}
     */
    public function getFinishedOn()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinishedOn', []);

        return parent::getFinishedOn();
    }

    /**
     * {@inheritdoc}
     */
    public function setCreatedAt($createdAt)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritdoc}
     */
    public function getCreatedAt()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritdoc}
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritdoc}
     */
    public function getUpdatedAt()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritdoc}
     */
    public function setJackpot(\Entity\Jackpot $jackpot = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJackpot', [$jackpot]);

        return parent::setJackpot($jackpot);
    }

    /**
     * {@inheritdoc}
     */
    public function getJackpot()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJackpot', []);

        return parent::getJackpot();
    }

    /**
     * {@inheritdoc}
     */
    public function setLongestBidWinnerUser(\Entity\User $longestBidWinnerUser = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongestBidWinnerUser', [$longestBidWinnerUser]);

        return parent::setLongestBidWinnerUser($longestBidWinnerUser);
    }

    /**
     * {@inheritdoc}
     */
    public function getLongestBidWinnerUser()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongestBidWinnerUser', []);

        return parent::getLongestBidWinnerUser();
    }

    /**
     * {@inheritdoc}
     */
    public function setLastBidWinnerUser(\Entity\User $lastBidWinnerUser = null)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastBidWinnerUser', [$lastBidWinnerUser]);

        return parent::setLastBidWinnerUser($lastBidWinnerUser);
    }

    /**
     * {@inheritdoc}
     */
    public function getLastBidWinnerUser()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastBidWinnerUser', []);

        return parent::getLastBidWinnerUser();
    }

    /**
     * {@inheritdoc}
     */
    public function getUsers()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }
}
