<?php

namespace Proxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Jackpot extends \Entity\Jackpot implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'id', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'title', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'amount', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'minPlayersRequired', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'durationSetting', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'gameClockTime', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'doomsDayTime', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'gameClockRemaining', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'doomsDayRemaining', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'gameStatus', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'uniqueId', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'startedOn', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'status', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'createdAt', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'updatedAt', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'createdBy', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'updatedBy', 'jackpotGames', 'battleLevels'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'id', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'title', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'amount', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'minPlayersRequired', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'durationSetting', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'gameClockTime', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'doomsDayTime', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'gameClockRemaining', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'doomsDayRemaining', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'gameStatus', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'uniqueId', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'startedOn', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'status', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'createdAt', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'updatedAt', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'createdBy', '' . "\0" . 'Entity\\Jackpot' . "\0" . 'updatedBy', 'jackpotGames', 'battleLevels'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Jackpot $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', [$amount]);

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', []);

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinPlayersRequired($minPlayersRequired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinPlayersRequired', [$minPlayersRequired]);

        return parent::setMinPlayersRequired($minPlayersRequired);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinPlayersRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinPlayersRequired', []);

        return parent::getMinPlayersRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function setDurationSetting($durationSetting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDurationSetting', [$durationSetting]);

        return parent::setDurationSetting($durationSetting);
    }

    /**
     * {@inheritDoc}
     */
    public function getDurationSetting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDurationSetting', []);

        return parent::getDurationSetting();
    }

    /**
     * {@inheritDoc}
     */
    public function setGameClockTime($gameClockTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGameClockTime', [$gameClockTime]);

        return parent::setGameClockTime($gameClockTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getGameClockTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGameClockTime', []);

        return parent::getGameClockTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoomsDayTime($doomsDayTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoomsDayTime', [$doomsDayTime]);

        return parent::setDoomsDayTime($doomsDayTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoomsDayTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoomsDayTime', []);

        return parent::getDoomsDayTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setGameClockRemaining($gameClockRemaining)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGameClockRemaining', [$gameClockRemaining]);

        return parent::setGameClockRemaining($gameClockRemaining);
    }

    /**
     * {@inheritDoc}
     */
    public function getGameClockRemaining()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGameClockRemaining', []);

        return parent::getGameClockRemaining();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoomsDayRemaining($doomsDayRemaining)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoomsDayRemaining', [$doomsDayRemaining]);

        return parent::setDoomsDayRemaining($doomsDayRemaining);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoomsDayRemaining()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoomsDayRemaining', []);

        return parent::getDoomsDayRemaining();
    }

    /**
     * {@inheritDoc}
     */
    public function setGameStatus($gameStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGameStatus', [$gameStatus]);

        return parent::setGameStatus($gameStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getGameStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGameStatus', []);

        return parent::getGameStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniqueId($uniqueId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniqueId', [$uniqueId]);

        return parent::setUniqueId($uniqueId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueId', []);

        return parent::getUniqueId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartedOn($startedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartedOn', [$startedOn]);

        return parent::setStartedOn($startedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartedOn', []);

        return parent::getStartedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\Entity\User $createdBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy(\Entity\User $updatedBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getJackpotGames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJackpotGames', []);

        return parent::getJackpotGames();
    }

    /**
     * {@inheritDoc}
     */
    public function getBattleLevels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBattleLevels', []);

        return parent::getBattleLevels();
    }

}
